creachadair/jrpc2

- README.md
This package was apparently removed in https://github.com/creachadair/jrpc2/commit/8c9d845424b1440f8f0ce7bc204c5bdabbe4756a
> Readme: Remove outdated link to proxy pkg

- go.mod
This is mostly to make consumer's Go tooling to issue a helpful message about version requirement, rather than just compilation errors.
Related to https://github.com/creachadair/jrpc2/commit/81dd53f1d58b55d5b1c0a3c8ccc5cb2c818c3a0c and https://github.com/creachadair/jrpc2/commit/3ce3f1c20ee71a8efe0d3e3aeafe4711852c9545
> go.mod: Bump requirement to Go 1.13

- channel/channel_test.go
- channel/hdr.go
Rework the Header framing, moving the existing implementation to StrictHeader. The latter still reports an error for content-type mismatches, but does so in a way that permits the caller to detect it.
The Header framing is now a light wrapper for StrictHeader that filters out these mismatches. The LSP framing now permits the sender to omit the content-type field without reporting an error.
Addresses #4.
> Allow header framed messages to omit Content-Type.

- opts.go
- server.go
Add a server option to provide callbacks for each request received from the client and its corresponding response (if any). This supports debugging and also RPC capture for replay testing.
Addresses #2.
> Add hooks for structured RPC logging

- base.go
- jrpc2_test.go
I was implementing slightly more complex I/O logic (partially to make server mock-able) and I managed to mistakenly mix up client and server writers and readers and it wasn't clear to me immediately that the server was processing its own responses as requests until I dug deeper and exposed some more details in the error message.
I feel this could save some other people valuable debugging time.
> Report what extra fields are passed in error

- jrpc2_test.go
- server.go
Addresses #11. The Wait method filters out normal channel close errors, along
with explicit calls to Stop.  This is usually what you want, but means the
caller can't distinguish explicit shutdown from channel closes.
Add a WaitStatus method that includes more detail, and re-implement Wait in
terms of it.
> server: Allow caller to distinguish shutdown from close

- server/simple.go
- server/simple_test.go
Inspired by this comment thread: https://github.com/creachadair/jrpc2/pull/14#pullrequestreview-378053953
There are a couple differences worth noting here from the outline in that thread:
- Rather than exposing Wait and WaitStatus, this implementation runs the server to completion. A caller that doesn't want to wait can run it in a goroutine (`go s.Run(ch)`) and then the service alone is responsible for handling the return status.
- No work is done until the server is started, so that it's safe to abandon a constructed wrapper without orphaning resources the service may have allocated.
> server: add a one-shot service wrapper

- base.go
- client.go
- internal_test.go
- opts.go
- server.go
Updates #18. As a first step toward allowing a server to "push" calls to a
client, unify the jrequest and jresponse types into a single jmessage type that
represents protocol objects of either type. This has the pleasant side-effect
of simplifying the code for marshaling and unmarshaling as well.
No functional changes are intended, and all the tests still pass.
> Consolidate protocol messages into a single type.

- base.go
- doc.go
- jrpc2_test.go
- opts.go
- server.go
An attempt to address #20.
When issuing a batch of requests, keep track of the number that are valid notifications, and do not issue to any handler for the batch until all notifications received in previous batches have completed.
This ensures a sensible partial order on notifications. Multiple notifications in a single batch can still be executed in parallel, but notifications across batches are no longer concurrent.
Before merging:
> Add a barrier constraining execution order for notifications.

- base.go
- client.go
- cmd/examples/server/server.go
- ctx.go
- doc.go
- jrpc2_test.go
- opts.go
- server.go
Fixes #18.
Note that this PR includes some breaking API changes, specifically that:
- `jrpc2.ServerPush` has been renamed `jrpc2.PushNotify`
- `(*Server).Push` has been renamed `(*Server).Notify`
- `jrpc2.ErrNotifyUnsupported` has been renamed `jrpc2.ErrPushUnsupported`
> Experimental support for server-side callbacks

- regression_test.go
- server.go
Fixes #27. Since #24, the server holds its lock during dispatch to wait for previously-issued notifications to settle. This is necessary to ensure a sensible order of operations; however, it interacts badly with a notification handler that uses the jrpc2.CancelRequest helper: That function itself acquires the server lock, and the two (may) deadlock.
To avert this problem, wait on the notification barrier outside the lock. Add a regression test against the original bug.
> Fix a deadlock between handlers and server.

- base.go
- client.go
- jrpc2_test.go
- opts.go
When set, the new OnCancel callback overrides the client's built-in support for
sending rpc.cancel notifications. The hook can implement the same functionality
or take other actions using the client and the cancelled response.
Related changes:
- Add tests for OnCancel hook handling.
- Fix up some comment typos.
> Add a cancellation callback to ClientOptions.

- base.go
- examples_test.go
- internal_test.go
- jrpc2_test.go
Fixes #31.
Commit 78545e2a disallowed unknown struct fields when unmarshaling parameters. The check could be bypassed by implementing the `json.Unmarshaler` interface, but the need to do so causes friction for implementations of LSP, which has a loose and rapidly-changing schema (see #5, #31).
This changes the default back to ignoring unknown fields, and adds a new optional interface to re-enable strict checking without a custom unmarshaler.
N.B.: This is a breaking API change.
> Improve handling of unknown fields in parameter structs

- jrpc2_test.go
- server.go
Prior to this change, the server checked the ID of an inbound request before
checking whether it is a callback response. This could result in a spurious
error if the callback happened to use the same ID as an in-flight request.
Update the tests to ensure they tickle this case, and fix the order of checks
so that we do not check for duplicate IDs until AFTER filtering matches of a
push response.
Fixes #36.
> Fix request validation checks for push calls.

- client.go
- opts.go
- regression_test.go
- server.go
Prior to this change, a client callback handler that panics could cause a server running in the same process to stall waiting for a reply, if the panic was absorbed at a higher level without cleaning up the client.
Although this combination of conditions is less common, it can be tricky to debug. To avert this, recover a panic from the callback handler and convert it into an error back to the server.
In addition, the server was not cleaning up pending push-calls when shutting down in response to a client connection termination. This also fixes that problem on the server side.
Fixes #41
> Handle panics in client-side callback handlers.

- ctx.go
- jrpc2_test.go
- special.go
Add a top-level `ServerFromContext` function that recovers the `*Server` value from
the context passed to a handler.
Related changes:
- Clean up some redundant flag checks in the context handlers.
- Rewrite the existing context handlers in terms of this new function.
- Add a top-level `CancelRequest` method on the `Server`.
Fixes #38.
> Add a function to expose a Server to its handlers.

- client.go
An attempt to address #47.
The server does this check during delivery, but the client didn't need to before callbacks were added.
> client: avoid writing to a closed channel when handling callbacks

- client.go
- doc.go
- internal_test.go
- jrpc2_test.go
- opts.go
- server.go
- special.go
This is an implementation of #49.
Clients can use the `OnCancel` hook to propagate cancellation signals to the server.
Handlers can use the `CancelRequest` method to implement cancellation on the server.
> Remove the non-standard built-in cancellation protocol

- base.go
- cmd/examples/client/client.go
- cmd/examples/server/server.go
- cmd/jcall/jcall.go
- jrpc2_test.go
Instead of returning only the inferred network type, return also the address
that the caller passed in. This allows a call to jrpc2.Network to be passed
directly in argument position to net.Listen, without having to echo the address
explicitly.
This is a breaking change for uses of the Network function, but does not affect
any other part of the module API.
> Update the Network helper to return a tuple.

- cmd/examples/http/server.go
- jhttp/bridge.go
- jhttp/example_test.go
- jhttp/jhttp_test.go
This change is in support of #46. It is a breaking change to the jhttp.Bridge API.
The purpose of a jhttp.Bridge is to convey requests from an HTTP handler into a
JSON-RPC server. The way I had implemented it, however, required interposing a
client, which complicated the logic of forwarding.
Instead of requiring a client, the Bridge now takes an unstarted server, and
starts it up on an in-memory channel. We still have to parse the requests to
detect whether there are any calls, since HTTP requires a response regardless
of whether the JSON-RPC server replies, but we no longer need to virtualize
request IDs or re-marshal the request values.
> jhttp: Re-work the Bridge interface to require less plumbing.

- jrpc2_test.go
- server.go
Prior to this change, calls pushed from the server to the client would ignore
the context passed to the Callback method. This meant that if the client did
not reply (for example, the client has no support for push calls), the callback
would block forever.
This change makes pending callbacks on the server respect the context that was
passed to the Callback method: When it ends, if the call has not yet received a
response, it is delivered an error from the context and resolved.
Update the documentation on Callback to recommend setting a timeout or deadline
on the context, in cases where the client might not reply.
> server: Handle context termination for pending callbacks.

- jrpc2_test.go
- opts.go
- server.go
Previously, the server used a background context as the basis for a request
context. This change adds a NewContext server option that the server now uses
instead. The default is to still use a background context.
> server: Add an option to create a base request context.

- base.go
- cmd/examples/http/server.go
- jhttp/bridge.go
- jhttp/example_test.go
- jhttp/jhttp_test.go
This change mostly reverts the changes to `jhttp.Bridge` from #52, but respecting some of the other changes in the package since that was merged. This fixes the problems with ID collisions, by restoring the virtualization.
The resulting interface is different from both the original interface (where the bridge accepted a client) and the "simplified" interface (where the bridge accepts a server). Now the bridge behaves more like the local server from the `server` package, except that it retains awareness of the HTTP infrastructure.
Fixes #57.
> Revert the interface changes to jhttp.Bridge from #52.

- handler/handler.go
- handler/handler_test.go
- handler/positional.go
Add a new top-level function handler.Positional. Like Check, it accepts a function to be wrapped as a jrpc2.Handler. Unlike Check, this function allows positional arguments, which it implements by constructing a wrapper that takes a synthetic struct type as its argument, and redirects the fields of the struct to the positional arguments of the original function when the wrapper is called.
> Support positional argument in wrapped handlers

- client.go
- ctx.go
- jrpc2_test.go
- opts.go
- server.go
Change the implementation of the client-side callback handler to allow multiple callback handlers to execute concurrently.
Related changes:
- Add a function to expose the client to the callback handler (jrpc2.ClientFromContext). This allows the callback handler to call "up" into the server.
- Fix a callback plumbing bug in the server.
- Add tests to exercise concurrent callback handling.
> Add support for concurrent callback handlers in the Client

- client.go
- jrpc2_test.go
- opts.go
- server.go
The intent of these options was to tolerate calls to/from JSON-RPC 1.0
implementations. That alone isn't enough for interoperability, however.
For example:
- Server replies still contain the v2 version marker, which (some) v1 clients
do not accept.
- The v2 Error object has a stricter structure than v1, and the client only
accepts v2.
Since this library implements v2 specifically, I do not think it's worthwhile
to add extra plumbing for those cases (e.g., tracking v1 shape through the
handler, tolerating arbitrary Error geometry). On that basis, the tolerance
settings are not carrying their weight.
For context see #44.
Updates #46
> Remove the client and server "AllowV1" settings.

- jrpc2_test.go
- opts.go
- server.go
There is no strong reason to make the server handle this concern separately.
> Remove the CheckRequest server option.

- handler/handler.go
- handler/handler_test.go
- handler/positional.go
- json_test.go
Extend the generated wrapper for a positional function to accept parameters
encoded as a JSON array of the correct length. When decoding the params, if
names are provided and the value is an array of the correct length, rewrite the
array into an equivalent object with the names mapped.
This works because the positional names preserve the original order, and ensure
that we do not introduce any unknown fields.
> handler: support array arguments in positional wrappers

- channel/channel_test.go
- go.mod
- go.sum
- internal_test.go
- jhttp/jhttp_test.go
- jrpc2_test.go
- server/local_test.go
- server/loop_test.go
Use the https://godoc.org/github.com/fortytw2/leaktest package to test for
leaked goroutines at exit in tests that use them.
> Add goroutine leak checking to unit tests.

- jhttp/bridge.go
- jhttp/jhttp_test.go
Add a new hook to the Bridge options to allow the caller to handle parsing the
HTTP request into JSON-RPC requests. Remove the old content-type check hook.
The request check hook remains, but setting either it or the new parse hook
disables the default method POST and content-type checks; the hooks are now
fully responsible for checking the structure of the request.
Without either of these hooks set, the default behaviour does not change.
> jhttp: extend and simplify request processing hooks

- server/loop.go
- server/loop_test.go
Update the Accepter interface to take a context argument.
This is a breaking change to the interface, but NetAccepter works
without change, so most existing use is not affected.
Rework Loop as LoopContext, which takes a context argument to
govern the lifecycle of the loop itself. Retain Loop as a wrapper
for LoopContext with a background context.
Update and clean up tests.
> server: update context plumbing

- jhttp/bridge.go
- jhttp/jhttp_test.go
There is no real point in having two separate hooks, keep the more general of the two.
> jhttp: Remove the CheckRequest bridge hook

- jhttp/getter.go
- jhttp/getter_test.go
The Getter type bridges HTTP GET requests to JSON-RPC.  Unlike a Bridge, the
method and parameters rely on the URL rather than the request body.  Results
are written back to the client without JSON-RPC request frames.
The default request parser treats query fields as plain strings; the caller can
plug in more specific parsing via options.
> jhttp: add a Getter type to handle GET requests

- queue.go
- server.go
Use a singly-linked queue for pending request batches.
Use a free list to save allocations in the queue.
Saves 1 to 4 percent in round trip benchmarks.
> Replace container/list with a type-specific queue.

- channel/channel.go
Document that messages sent to a direct channel are not copied, and that the
caller is responsible for making one if necessary. The client and server do not
require copies, and this saves 2 to 4 percent on memory use in benchmarks.
> channel: Direct channels no longer copy their input

- base.go
- jrpc2_test.go
- json.go
The previous implementation did not work correctly. Instead of just adding the
strictFielder method, actually implement json.Unmarshaler.
Update the test cases to correctly exercise the intended behaviour.
> Fix implementation of StrictFields.

- base.go
- error.go
- jrpc2_test.go
- regression_test.go
- server.go
Previously, if two or more calls arrived in a single batch with the same request ID, the server would process the first one and report the rest as having duplicate IDs.
This is subtly wrong, in that the client has no way of knowing which of the duplicates should get the successful call, and which should get the errors. Although a client sending such requests is already wrong, this makes the error harder to debug.
Instead, check for duplicates within the batch during assignment, and fail all the colliding requests.
- Add a regression test for duplicate requests in a single batch.
- Add a shared common error for InvalidParams.
- Add a shared error base for NoSuchMethod.
> server: handle duplicate request IDs within a single batch

- regression_test.go
- server.go
Previously, a notification handler that issues a call back to the client could
block delivery of the reply for its own callback: The barrier we use to
preserve issue order means another batch cannot be issued to the dispatcher
until all previously-issued notifications have completed.
To prevent the handler from deadlocking itself in this case, filter out
response messages from the client when the input is received, rather than
enqueuing them with the handlers. This basically just moves the existing logic
earlier in the transaction, but it means replies can be delivered even if the
barrier is active.
Add regression test for deadlock bug.
Fixes #78.
> Front-load handling of callback responses from the client.

- client.go
- error.go
- examples_test.go
- handler/example_test.go
- handler/handler_test.go
- internal/testutil/testutil.go
- internal/testutil/testutil_test.go
- internal_test.go
- jhttp/bridge.go
- jhttp/jhttp_test.go
- jrpc2_test.go
- json.go
- server.go
Add a new ParsedRequest type and return that instead of Request.
The latter is intended for consumption by Handler methods, and is hard to use
effectively in other contexts.  The new type exposes validation errors that
occur during parsing and allows the caller to detect specific problems with
each individual request in a batch separately.
This change also allows us to consolidate the checking of version errors, and
to remove most of the special case checks inside the client and server.
- Update the jhttp.Bridge to use the new ParsedRequest type.
- Update test cases. In cases where we really needed a jrpc2.Request, use the
newly introduced internal/testutil package, which uses the server plumbing to
render a request.
Fixes #80.
> Rework the jrpc2.ParseRequests function.

- handler/handler.go
- handler/handler_test.go
- handler/positional.go
- jrpc2_test.go
Remove the top-level Struct and NewStruct constructors, and instead fold
the special case for struct arguments into Check. Update test cases to
exercise both input formats.
This is a breaking change to the handler package API.
> handler: collapse NewStruct into Check

- code/code.go
- code/code_test.go
In practice any package that wants to define custom codes has to keep track of them anyway, so that the client can coordinate with the server. The additional hook for cosmetics in the default error string is just not worthwhile.
Updates #46.
> code: remove the code registration hooks

- handler/handler.go
- handler/positional.go
> handler: remove implementation details from docs

- README.md
- base.go
- client.go
- code.go
- code_test.go
- error.go
- examples_test.go
- handler/handler.go
- handler/handler_test.go
- internal_test.go
- jhttp/getter.go
- jrpc2_test.go
- json.go
- opts.go
- server.go
After removing the registration hooks in #91, what is left of the code package is too small to deserve its own identity. Collapse the package into the root jrpc2 package.
- Rename the code.FromError helper to jrpc2.ErrorCode.
- Update documentation.
Updates #46.
> Collapse the code package into jrpc2.

- base.go
- channel/channel.go
- channel/hdr.go
- client.go
- code.go
- ctx.go
- error.go
- internal_test.go
- json.go
- opts.go
- server.go
- server/loop.go
> Update doc comments throughout the module.

- client.go
- jrpc2_test.go
- opts.go
A client can be stopped by calling its Close method, or by a failure of its
connection to the server. The user of the client does not have a way to handle
this gracefully.
Add an IsStopped method to the *jrpc2.Client, allowing the caller to check
whether the client is still alive explicitly.
Add an optional OnStop callback that will be invoked when the client closes,
allowing the caller to handle cleanup tasks automatically.
Updates #102
> client: improve handling of stopped clients

- jhttp/bridge.go
- jhttp/jhttp_test.go
Accept "utf8" and "utf-8".
Fixes #110.
> jhttp: allow content-type to include a charset

- handler/handler.go
- handler/handler_test.go
- handler/positional.go
Add a new AllowArray option to handler.FuncInfo controlling whether the decoder
will allow array notation for struct arguments. The default is true, so that
existing use is not affected.
When true (the default), the decoder allows the arguments for a struct to be
passed as a JSON array and maps the corresponding values to the struct fields
in order of declaration. This is the existing behaviour.
When false, the decoder reports an error for a struct-valued argument when the
parameter value is an array.
Updates #113
> handler: add an option to disallow array-based parameters
